fix: windows build error
# Error
[        ]   telosnex.dir\Debug\generated_plugin_registrant.obj
[ +167 ms]   telosnex.vcxproj -> C:\Users\jpohh\dev\telosnex\build\windows\x64\runner\Debug\telosnex.exe
[   +6 ms] _CopyOutOfDateSourceItemsToOutputDirectoryAlways:
[   +1 ms]   Copying file from
"C:\Users\jpohh\dev\telosnex\build\windows\x64\packages\Microsoft.Web.WebView2\build\native\x64\WebView2Loader.dll"
to "C:\Users\jpohh\dev\telosnex\build\windows\x64\runner\Debug\WebView2Loader.dll".
[   +2 ms] FinalizeBuildStatus:
[   +2 ms]   Deleting file "telosnex.dir\Debug\telosnex.tlog\unsuccessfulbuild".
[        ]   Touching "telosnex.dir\Debug\telosnex.tlog\telosnex.lastbuildstate".
[        ] Done Building Project "C:\Users\jpohh\dev\telosnex\build\windows\x64\runner\telosnex.vcxproj" (default
targets).
[        ] Done Building Project "C:\Users\jpohh\dev\telosnex\build\windows\x64\ALL_BUILD.vcxproj" (default
targets) -- FAILED.
[        ] Done Building Project "C:\Users\jpohh\dev\telosnex\build\windows\x64\INSTALL.vcxproj" (default targets)
-- FAILED.
[  +16 ms] Build FAILED.
[   +2 ms] "C:\Users\jpohh\dev\telosnex\build\windows\x64\INSTALL.vcxproj" (default target) (1) ->
[        ] "C:\Users\jpohh\dev\telosnex\build\windows\x64\ALL_BUILD.vcxproj" (default target) (3) ->
[        ] "C:\Users\jpohh\dev\telosnex\build\windows\x64\plugins\nutdart\shared\nutdart.vcxproj" (default target)
(26) ->
[        ] (ClCompile target) ->
[        ]
C:\Users\jpohh\dev\telosnex\windows\flutter\ephemeral\.plugin_symlinks\nutdart\src\win32\window_manager.cc(92,46):
warning C4244: 'argument': conversion from 'const int64_t' to 'int', possible loss of data
[C:\Users\jpohh\dev\telosnex\build\windows\x64\plugins\nutdart\shared\nutdart.vcxproj]
[        ]
C:\Users\jpohh\dev\telosnex\windows\flutter\ephemeral\.plugin_symlinks\nutdart\src\win32\window_manager.cc(92,39):
warning C4244: 'argument': conversion from 'const int64_t' to 'int', possible loss of data
[C:\Users\jpohh\dev\telosnex\build\windows\x64\plugins\nutdart\shared\nutdart.vcxproj]
[        ]
C:\Users\jpohh\dev\telosnex\windows\flutter\ephemeral\.plugin_symlinks\nutdart\src\win32\window_manager.cc(111,36):
warning C4244: 'argument': conversion from 'const int64_t' to 'int', possible loss of data
[C:\Users\jpohh\dev\telosnex\build\windows\x64\plugins\nutdart\shared\nutdart.vcxproj]
[        ]
C:\Users\jpohh\dev\telosnex\windows\flutter\ephemeral\.plugin_symlinks\nutdart\src\win32\window_manager.cc(111,33):
warning C4244: 'argument': conversion from 'const int64_t' to 'int', possible loss of data
[C:\Users\jpohh\dev\telosnex\build\windows\x64\plugins\nutdart\shared\nutdart.vcxproj]
[        ] "C:\Users\jpohh\dev\telosnex\build\windows\x64\INSTALL.vcxproj" (default target) (1) ->
[        ] "C:\Users\jpohh\dev\telosnex\build\windows\x64\ALL_BUILD.vcxproj" (default target) (3) ->
[        ] "C:\Users\jpohh\dev\telosnex\build\windows\x64\plugins\nutdart\shared\nutdart.vcxproj" (default target)
(26) ->
[        ] (ClCompile target) ->
[        ]
C:\Users\jpohh\dev\telosnex\windows\flutter\ephemeral\.plugin_symlinks\nutdart\src\win32\window_manager.cc(47,17):
error C2664: 'int GetWindowTextW(HWND,LPWSTR,int)': cannot convert argument 2 from 'CHAR *' to 'LPWSTR'
[C:\Users\jpohh\dev\telosnex\build\windows\x64\plugins\nutdart\shared\nutdart.vcxproj]
[        ]     4 Warning(s)
[        ]     1 Error(s)
[        ] Time Elapsed 00:00:29.09
[  +45 ms] Building Windows application... (completed in 36.2s)
[+3321 ms] Error: Build process failed.
[   +3 ms] "flutter run" took 53,003ms.
[  +78 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:34:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:867:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1563:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:494:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:431:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:98:11)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:102:3)
           <asynchronous suspension>

[   +1 ms] Running 3 shutdown hooks
[  +21 ms] Shutdown hooks complete
[  +97 ms] exiting with code 1

# Diagnosis
Perfect! I've fixed the compilation error by:

1. **Changed `CHAR` to `WCHAR`**: This ensures we're using wide characters that match what `GetWindowText` (which maps to `GetWindowTextW`) expects.

2. **Added proper string conversion**: Since the function needs to return a `std::string` (narrow string), I added code to convert the wide character string to UTF-8 using `WideCharToMultiByte`.

3. **Added proper memory management**: I made sure to delete the allocated memory in both success and failure paths.

The fix addresses the core issue:
- **Before**: `GetWindowText(hWnd, windowTitle, BUFFER_SIZE)` where `windowTitle` was `CHAR*`
- **After**: `GetWindowText(hWnd, windowTitle, BUFFER_SIZE)` where `windowTitle` is `WCHAR*`

This should resolve the compilation error. The warnings about `int64_t` to `int` conversion are just warnings and won't prevent the build from succeeding, but the `CHAR*` to `LPWSTR` error was a blocking compilation error that's now fixed.

You can now try building your Flutter app again and it should compile successfully!